#!/bin/bash

set_commands() {
  KUBECTL=${KUBECTL:-kubectl}
  FZF=${FZF:-fzf}
}

get_running_pods() {
    "$KUBECTL" get pods --field-selector=status.phase=Running | cut -d " " -f 1 | tail -n +2
}

select_pod() {
    local pods pod_count

    pods=$(get_running_pods)
    pod_count=$(echo "$pods" | wc -l)
    if [ "$pod_count" -ne "0" ]; then
        echo "$pods" | "$FZF"
    fi
}

get_containers() {
    local pod
    pod="$1"
    "$KUBECTL" get pods "$pod" -o jsonpath='{.spec.containers[*].name}'  | tr ' ' '\n'
}

select_container() {
    local pod containers container_count
    pod="$1"
    containers=$(get_containers "$pod")
    container_count=$(echo "$containers" | wc -l)
    if [ "$container_count" -eq "1" ]; then
        echo "$containers"
    else
        echo "$containers" | "$FZF"
    fi
}

run_shell() {
    local pod container
    pod="$1"
    container="$2"
    exec "$KUBECTL" exec -it "$pod" -c "$container" -- bash
}

main() {
    local pod container

    set_commands

    pod=$(select_pod)
    if [ "$pod" == "" ]; then
        exit 1
    fi

    container=$(select_container "$pod")
    if [ "$container" == "" ]; then
        exit 1
    fi

    run_shell "$pod" "$container"
}

main "$@"
